### ISSUE TITLE
Канал связи

### ISSUE THREAD

**Issue by yuristsepaniuk** [PabloDeCortes/Something_Strange#1]
Привет, Паша! Спрашивай :)

**Comment by PabloDeCortes** [comment]
Привет!) В 11-й таске на 10 баллов надо было сделать собственный store для работы с diskdb. Дело в том, что есть connect-diskdb, а у express-session можно задать параметр store: {...} и там описать бд, т.е. можно обойтись стандартными функциями. Сейчас я использую именно connect-diskdb, но он записывает в cookie целиком всего юзера вместе с паролями, id и т.д. Я, конечно, сделал и собственный store, который записывает только sessionID, а в бд по этом sessionID хранится уже сам юзер. Но дело в том, что при каждом запуске сервера сессия-то меняется, и получается, что надо перезаписывать sessions.json, нормально ли это? Т.е. мы перезаписываем целиком бд после того, как меняется sessionID. И не совсем понятно, как работать с сессиями и бд, когда пользователей будет много. Насколько я понял, по умолчанию используется default store, который у каждого пользователя свой, а сейчас мы используем бд и сейчас у меня, по сути, будет просто перезаписывать пользователя каждый раз, причём это делает сам connect-diskdb. Когда я заходил под разными пользователями, он их просто перезаписывал, т.е. в бд хранилась всегда одна запись.

**Comment by yuristsepaniuk** [comment]
Короткий вопрос:
"Но дело в том, что при каждом запуске сервера сессия-то меняется, и получается, что надо перезаписывать sessions.json, нормально ли это?"

Это в твоей собственной реализации? Или в реализации connect-diskdb?

**Comment by PabloDeCortes** [comment]
Это реализация connect-diskdb, поэтому я сделал точно так же.

**Comment by yuristsepaniuk** [comment]
давай еще раз:
1. cookie хранит SID, никто ее не меняет в браузере.
2. сервер рестартанул и данные в diskdb о сессиях уничтожены?
3. приходит эта cookie с SID и такого юзера нет, нужно сделать новый SID и выслать юзеру?

У тебя такие шаги получились?
NOTE: про одного юзера в сторе пока не говорим.

**Comment by yuristsepaniuk** [comment]
Это совсем плохо, такого быть не должно. Насчет нескольких юзеров.

1. Пришел Юра и получил SID:yuri
2. yuri получил новости.
3. Пришел Паша и получил SID:pasha. В этот момент SID:yuri удалился из db?

**Comment by PabloDeCortes** [comment]
"сервер рестартанул и данные в diskdb о сессиях уничтожены" я сделал так только потому, что так было заложено в connect-diskdb, но это исправить две секунды) Правильно должно быть так, как я понял:
1. БД не чистится вообще в принципе.
2. В БД хранится пара ключ-значение, где ключ это SID, значение — юзер.
Так?

**Comment by yuristsepaniuk** [comment]
Верно, Паша! Так должно быть сделано, потому что на продакшене падающий node модуль - это частое явление. Существуют процессы, которые мониторят упавшие и срочно переподнимают их.

Поэтому все верно:
1. не чистим db при перезапуске, потому что другие nodes в кластере продолжают обслуживать юзеров твоих. Т.е. мы говорим про продакшен, нам не нужно реализовывать кластер. Нужен просто один нод, который легко можно будет потом добавить в кластер.
2. В базе храним ключ-значение, как ты сказал, верно!

**Comment by PabloDeCortes** [comment]
Спасибо, всё понял, исправил)

**Comment by sergey-moiseyenko** [comment]
Юрий, привет, хотел уточнить реализацию auth.
Так как мы разрабатываем BE по принципам REST, то использование passport-local и сессий не подходит под архитектуру нашего приложения (одно из требований к архитектуре REST: информация о состоянии клиента на сервере не хранится).

Считаю, что для этого больше подходит passport-http или passport-jwt. Что скажешь?

**Comment by sergey-moiseyenko** [comment]
https://github.com/sergey-moiseyenko/news-portal-api/issues/3

**Comment by PabloDeCortes** [comment]
Юра, привет. Такой вопрос назрел у меня. Я сейчас по сути всё сделал, но я не понимаю одной вещи. Паспорт проверяет только наличие пользователя в базе, если проверка пройдена, то сериализует его в бд. Десериализация же не работает, так как надо(req.session = undefined после перезагрузки и десериализация не хочет работать) поэтому пришлось писать собственные куки, в которые заносится SID, и потом с ними же работать на фронте при проверке. 
P.S. С connect-diskdb я маленечко ошибся, там всё работает как надо, только хранит обычный массив, а не ассоциативный.

**Comment by yuristsepaniuk** [comment]
1. на фронте не нужно читать SID вообще, он просто передается на сервер.
2. если нужно написать привет юзер, то делается дополнительный запрос "дай мне юзаре по SID", приходит ответ { "data": { "user": "Vasia"} } и ты рисуешь привет Вася.

////////////
у паспорта несколько степов:
1. авторизовать при помощи отсылки формы (передаешь юзер-нейм и пассворд), получаешь SID в куках, получаешь req.user во всех объектах req.
2. должна произойти сериализация в базу следующим степом, passport вызывает сам твой метод serializeUser и передает туда первым параметром req.user, вторым параметром передает функцию done, которую ты должен вызвать, например done(null, user.id) - с тем с чем вызвал, то и запишешь в store базы. Там запись должна появиться такая SID - ключ, а значение id юзера.
3. прилетает второй запрос от браузера, в котором в куках только SID, паспорт (а точнее  express-session) ходит в тихую в store и достает по SID значение id юзера, потом passport  громко вызывает метод deserializeUser, передает параметр id, который тихо достал из базы и передает done функцию, которую ты должен вызвать. done(null, User.findById(id)). Так как ты достаешь юзера по id, ты просто вызываешь done с полным юзером. Паспорт втихую запишет его в req.user.


Проверь, по идее я не ошибаюсь, и отпиши если все так.

Удачи
-Юра

**Comment by PabloDeCortes** [comment]
Я на фронте только отправляю запрос на получение имени юзера из куки. На сервере уже из куки достаётся SID и проходит поиск по БД, достаётся юзернейм и передаётся в качестве ответа обратно фронту.
В req.user юзер лежит только пока сервер не перезапущен, как только сервер ребутается, то в req.user ничего не лежит, поэтому express-session не входит в store, хоть куки от предыдущей сессии(созданые автоматически) сохранились.

**Comment by yuristsepaniuk** [comment]
express-session должен входить в стор, может у тебя поменялся SID?

**Comment by PabloDeCortes** [comment]
Вот в этом-то и ступор. SID меняется и express-session в стор не входит

**Comment by yuristsepaniuk** [comment]
SID не должен меняться, нужно искать причину. может у тебя указан статический session secret.

**Comment by yuristsepaniuk** [comment]
точнее не указан, должен быть статический

**Comment by PabloDeCortes** [comment]
Вы напугали меня первым сообщением про secret. Нет, у меня указан статический. При перезагрузке сервера req.user == undefined

**Comment by yuristsepaniuk** [comment]
Павел, Вы не понимаете причину! Повторю req.user === undefined не является проблемой. Проблема есть в меняющемся SID. Вам нужно искать проблему, почему у Вас он поменялся.

Я посмотрел Ваш код, мне кажется у Вас проблема тут, зачем Вы используете cookie-parser. По всей видимости Вы пересоздали cookie и отослали новый SID на клиента. Или у Вашего куки недолгий срок службы или в том модуле Вы забыли указать cookie-parser какая стратегия хранения Вашего куки, max-age там и так далее. Я бы избавился от этого модуля, потому что читайте ниже:
(from express-session)
Note Since version 1.5.0, the cookie-parser middleware no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser.

**Comment by PabloDeCortes** [comment]
Добрый вечер. Я тут нашёл вот что: "MemoryStore is just for (rapid) development mode, because if your app restarts (process dies) you will lose all the session data (that resided in the memory of that process)." Получается, что сессия умирает после перезапуска приложения, поэтому SID и меняется каждый раз. В default store есть поле sessions, так вот после перезапуска оно пустое, но как только я вызову authenticate, оно заполняется функцией deserialize.

**Comment by yuristsepaniuk** [comment]
Паша, MemoryStore используется по умолчанию, если мы не включаем другой Store! Зачем нам нужен diskdb вообще? Потому что мы включили connect-diskdb, который сохраняет все в базу, если сервер перезапускается, то в базе данные хранятся, ничего не теряется. Ведь задача какая у студентов: используйте MemoryStore если хотите низкий бал, напишите Store над diskdb, если хотите высший бал. Ок, был найден connect-diskdb. 

НО ЗАЧЕМ? На лекции об этом говорили, вопросов не было.

Повторю, что было написано выше:
(from express-session)
Note Since version 1.5.0, the cookie-parser middleware no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser.

переведу: Начиная с версии 1.5.0, не нужно использовать cookie-parser. Основной момент ниже, cookie-parser может послужить причиной проблемы рассинхронизации ключа секрета между express-session и cookie-parser.

Используешь cookie-parser в котором не указал secret, используешь express-session в котором указал secret. Значит у них разные secret? Это и приводит к рассинхронизации сессии. Я посоветовал не использовать cookie-parser, потому что док по express-session говорит, мы теперь сами парсим куки и вам не нужен cookie-parser.


P.S. Если проблема в MemoryStore и SID, вопрос простой: мы понимаем задачу, которую решаем? :)

**Comment by PabloDeCortes** [comment]
"Потому что мы включили connect-diskdb" но мы же должны сами написать store для diskdb, а не подключать сторонний, или я не прав? Я пробовал cookie-parser убирать, я пробовал всё убирать и оставлять один express-session, SID менялся при каждом перезапуске сервера.

**Comment by yuristsepaniuk** [comment]
Давай по порядку, если оставить код как есть:

router.use(cookieParser());
router.use(expressSession({
    name: 'sid_always_changing',
    secret: 'pablodecortes',
    resave: false,
    saveUninitialized: true
}));

Работать не будет. Но если попробовать так?

router.use(cookieParser('pablodecortes'));
router.use(expressSession({
    name: 'sid_always_changing',
    secret: 'pablodecortes',
    resave: false,
    saveUninitialized: true
}));

То если в других местах ты правильно все сделал, SID не должен меняться. SID поменяется, если ты пришел на сервер без SID, такое может быть, только если cookie-parser не разобрал SID по секрету и сделал новый.

Если решение не поможет, то лучше отказаться от cookie-parser, обойтись новыми средствами express-session для разбора cookie.

Пример дебага:
1. я залогинился.
2. я убил сервер.
3. я поднял сервер.
4. я выполнил запрос с того же таба браузера на сервер, проверяю, что cookie ушел со старым SID.
5. ищу то злое место на сервере, которое генерирует новый SID, или просто удаляет старый.
6. соответственно я получаю 401 в браузер или что-то в этом роде. Или у меня падает сервер из-за undefined и тд.

**Comment by yuristsepaniuk** [comment]
P.S. я не знал про наличие connect-diskdb. Хотел, чтобы студенты поупражнялись с написанием своего Store.

**Comment by PabloDeCortes** [comment]
"cookieParser('pablodecortes')" пробовал ещё часа 2 назад. 

> Задача свелась к тому, что нужно написать свой собственный store, а по умолчанию даже не использовать, т.е. наш store должен использовать diskdb для хранения записи по SID'y, а сам SID наш store записывает в куки, я прав?)

**Comment by yuristsepaniuk** [comment]
код последний в мастере?

**Comment by PabloDeCortes** [comment]
Последний. Просто я не видел смысла добавлять с cookieParser('pablodecortes'), ведь он и без него работает(точнее не работает).

**Comment by yuristsepaniuk** [comment]
я смотрю код, минутку...

**Comment by PabloDeCortes** [comment]
Я тогда попробую store сделать собственный что ли, чтобы не мучать никого

**Comment by yuristsepaniuk** [comment]
скинь плиз юзера и пароль

**Comment by PabloDeCortes** [comment]
name: pablo
password: god

**Comment by yuristsepaniuk** [comment]
нескромно :)

**Comment by PabloDeCortes** [comment]
Я ожидал это услышать)

**Comment by yuristsepaniuk** [comment]
сходу проблема не по теме: getArticles достаются через PUT, а нужно через GET

**Comment by PabloDeCortes** [comment]
у GET нет тела, а мне нужно передать filterConfig

**Comment by yuristsepaniuk** [comment]
у меня работает норм сессия, какие у тебя степы? ты браузер закрываешь и открываешь? опиши детально степы как юзер

**Comment by PabloDeCortes** [comment]
1. Запускаю сервер
2. Открываю сайт
3. SID: 1234
4. Любые действия на сайте
5. SID: 1234
6. Ребут сервера
7. SID: fdsafbsdfasdbfabds

**Comment by yuristsepaniuk** [comment]
Ок, почему приложение работает?

**Comment by yuristsepaniuk** [comment]
В этом и вопрос?

**Comment by PabloDeCortes** [comment]
В смысле работает? SID поменялся, а паспорт сравнивает SID текущей сессии с той, что в куки, и, если они не совпадают, он не использует deserializeUser

**Comment by yuristsepaniuk** [comment]
ok, где падает приложение? за какую проблему зацепиться?

**Comment by PabloDeCortes** [comment]
Да нет же, я просто руками его перезагружаю и SID меняется.

**Comment by PabloDeCortes** [comment]
Давай по порядку, я сейчас подробно всё поясню, что не так. А то так и будем по кругу ходить.

**Comment by yuristsepaniuk** [comment]
жду...

**Comment by yuristsepaniuk** [comment]
<img width="811" alt="screen shot 2017-04-25 at 3 19 38 am" src="https://cloud.githubusercontent.com/assets/66004/25363792/12ca4a10-2966-11e7-9127-5c4b1b416947.png">

`SID=6bYaO8gW58XrQXudUdM0FN1I9ysbRE5Q; sid_always_changing=s%3A9_NYasicxZbJSEzK8M3W-bZJF936sfvW.Ju9Jm%2B2xPXwTWzyf2EavybijB3S6j9Z3KDn8wiiE5ws`

Я вижу, что SID всегда передается один и тот же, даже после рестарта сервера.
Все что sid_always_changing, это твое собственное и оно меняется, но тебе нужен первый SID из куки. То что ты генеришь, просто не используй, используй SID=6bYaO8gW58XrQXudUdM0FN1I9ysbRE5Q; Он не меняется и поддерживается через session-express.

**Comment by yuristsepaniuk** [comment]
Я ожидал увидеть в cookie только вот это SID=6bYaO8gW58XrQXudUdM0FN1I9ysbRE5Q; и больше ничего :)

**Comment by PabloDeCortes** [comment]
Запускаю сервер. Я захожу на сайт в первый раз, в куки ничего не лежит. Логинюсь, passport в куки ложит SID. SID у пользователя не меняется, пока я не перезагружу сервер. Т.е. пока сервер работает, req.user дёргает deserializeUser, а эта ф-я в свою очередь парсит куки и достаёт оттуда SID, поэтому SID'y я нахожу в db пользователя и пихаю его в req.user. Я перезахожу на сайт, всё работает, deserializeUser работает каждый раз при вызове пихает в req.user что-то, всё прекрасно. Я перезапускаю сервер, и всё, приехали, SID поменялся, в req.user ничего не лежит, потому что текущий SID не совпадает с тем, что лежит в куки и deserializeUser проводит забастовку. Т.е. как только сервер ляжет, у всех залогиненых пользователей выйдет.
p.s. SID — мой собственный, sid_always_changing — это не мой собственный))

**Comment by PabloDeCortes** [comment]
Мой SID не меняется, потому что я записываю его только один раз: когда логинюсь, а удаляю когда нажимаю выйти.

**Comment by PabloDeCortes** [comment]
А sid_always_changing так называется, потому что это SID сессии, а он меняется тогда, когда меняется сессия. Говорящее название:)

**Comment by yuristsepaniuk** [comment]
Ок, твою проблему воспроизвел и понял, перенесем на завтра беседу...

**Comment by PabloDeCortes** [comment]
Да, поздновато уже)

**Comment by yuristsepaniuk** [comment]
Кстати, а где тот самый подключенный Store? У тя ж MemoryStore :(

**Comment by yuristsepaniuk** [comment]
Кажется я понял в чем причина нашего рассинхрона.

1. найден connect-diskdb, если его включить, все работает, sid не меняется, кстати используй тот, который генерит express, т.е. говорящий.
2. если без connect-diskdb, то нужно писать свой собственный, который аналогичен connect-diskdb, и его все равно нужно будет подключить в конфиге expressSession(...), чтобы не юзался MemoryStore, иначе он будет мешать и постоянно переписывать тебе sid.
3. избавляйся от своего SID, используй sid_always_changing и назови его SID в конфиге.

**Comment by PabloDeCortes** [comment]
Я его убрал, я думал, что им нельзя пользоваться. Я же и говорю, что в этом вся проблема. SiD меняется=>new MemoryStore=>deserialize не работает. Таска сводится к написанию собственного модуля diskdb

**Comment by yuristsepaniuk** [comment]
именно, в этом и было недопонимание, оставить дефолтовый Store нельзя, задача сводится к написанию своего connect-diskdb.

**Comment by PabloDeCortes** [comment]
Т.е. просто подключить connect-diskdb это и есть задания на 10?

**Comment by PabloDeCortes** [comment]
Написать свой интереснее

**Comment by yuristsepaniuk** [comment]
Я не знал про его существование, печаль, что он есть, раз условие было такое, значит да, этого достаточно, чтобы получить 10. Но мы учимся не для 10 баллов. Да пиши свой, я заценю.

**Comment by PabloDeCortes** [comment]
Будет сделано, капитан) Спасибо огромное за разъяснения

**Comment by yuristsepaniuk** [comment]
отбой, пиши...

**Comment by yuristsepaniuk** [comment]
> у GET нет тела, а мне нужно передать filterConfig

Да, иногда так делают.

Вот какие есть пути решения:
1. Запрос разбиваем на два: PUT конфига в сессию (diskdb), второй запрос убегает на GET, но это неприятное решение. Тем не менее, оно соответствует REST принципу.
2. Если мы оставим только один GET, то все параметры просто нужно закодировать в GET. Проблема одна, GET ограничен по размеру.
3. Когда конфиг очень большой (это не наш случай), и не важен REST подход, то делают как ты.

Нужно пробовать решени 2, потом думать, что подходит лучше 1 или 3. Решение 3 отвлекает, ты ищешь GET запрос на лист, а его нет. Часто решение 3 принимают, когда FE строит конфиг, который прямо в базу и отправляется, но это опасно, потому что нужно предусмотреть проверку конфига на подлинность. А если ты разбиваешь на мелкие параметры (решение 2), то сервер отвечает за сборку конфига и отдает его на базу. Т.е. тут нужно принимать во внимание еще хакерские моменты.

**Comment by PabloDeCortes** [comment]
> Если мы оставим только один GET, то все параметры просто нужно закодировать в GET. Проблема одна, GET ограничен по размеру.
У GET'а ограничение стоит от длины url, а длина url у браузера у каждого своя. Chrome может скушать до 100к символов, даже не знаю, какой объект надо передавать, чтобы упереться в рамки ограничения. Тогда можно передавать в GET почти любой объект, надо лишь только закодировать его параметры, но удобно ли это? Сначала надо закодировать объект на клиенте(долго и нудно) и передать URL, в котором лежит наш объект, потом на сервере сидишь и парсишь каждый параметр query. А вот как получилось сделать всё то же самое через PUT, но немного быстрее и значительно удобнее:
На клиенте — JSON.stringify(obj).send;
На сервере — объект уже лежит в req.body, а ты только обращаешься к полям этого объекта.
Ну удобнее же, нет?)
p.s. Про хакерские моменты я немного не понял. Что будет страшного, если они (о боже:)) узнают теги или автора новости, которые к тому же отображаются всем и каждому на главной странице сайта.

**Comment by yuristsepaniuk** [comment]
Хакеры умнее нас, они учат все технологии подряд, например elasticsearch, если у тебя будет кодироваться запрос в elastic и как есть передаваться туда, то они могут поменять его так, что сервер ляжет, как минимум очевиден DoS. Если ты кодируешь в объект, то его по-хорошему нужно очищать от того, чего мы не ожидаем. 

Если у тебя в GET, то да, лишняя сборка на FE, лишняя пересборка на BE. Но для этого существуют инструменты готовые, пока о них не стоит.

**Comment by yuristsepaniuk** [comment]
Запостил пару коментов на твой последний комит
https://github.com/PabloDeCortes/Something_Strange/commit/a0dcab8c79695155abc416272a7e1cfbddee4fbb

**Comment by PabloDeCortes** [comment]
Я просто думал, что нам нужна хеш-таблица. Мне же проще стало только)

**Comment by yuristsepaniuk** [comment]
Думаю, что задание про хеш таблицы было в случае не использования diskdb. Если diskdb и хеш таблица, то нужно страдать. Так что давай без страданий))

**Comment by PabloDeCortes** [comment]
Уже исправлено)

**Comment by sergey-moiseyenko** [comment]
Юра, привет, у меня возникла проблема, что на клиенте в куки находится один и тот же sid, а на сервере sid постоянно меняется

**Comment by sergey-moiseyenko** [comment]
Может ли быть это связано, что бек и фронт на разных портах?

**Comment by sergey-moiseyenko** [comment]
То есть при каждом запросе req.sessionID меняется, хотя этого не должно происходить

**Comment by sergey-moiseyenko** [comment]
Для ясности, sid в бд и в куки не совпадают

**Comment by sergey-moiseyenko** [comment]
Нашел корень проблемы, клиент не прокидывает в заголовок запроса cookie

**Comment by sergey-moiseyenko** [comment]
Я предполагаю, что броузер запрещает передавать cookie при запросе на другой url(но это не точно)

**Comment by sergey-moiseyenko** [comment]
Опишу еще точнее траблу, прокидываю `cookie` в заголовке запроса(в `req.cookies` лежит моя кука), express не может вытянуть `sid`

**Comment by yuristsepaniuk** [comment]
@sergey-moiseyenko это потому делаешь больше, cors, готовься принимать вопросы на интервью по корсам. чтобы проблему пофиксить нужно добавить withCredentials true в XmlHttpRequest.

**Comment by sergey-moiseyenko** [comment]
Я указывал xhr.withcredentials = true

**Comment by sergey-moiseyenko** [comment]
А на беке просто сетал заголовок Access-Control-Allow-Credentials

**Comment by yuristsepaniuk** [comment]
@sergey-moiseyenko Что возвращает запрос за OPTIONS? Статус код интересует

**Comment by sergey-moiseyenko** [comment]
Был на паре, не смог раньше ответить, возвращает статус 200

**Comment by sergey-moiseyenko** [comment]
Возвращает статус `200`

**Comment by yuristsepaniuk** [comment]
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept, Cache-Control, Expires
Access-Control-Allow-Methods:GET, POST, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin:http://localhost:3000

Вот список хедеров, которые нужно возвращать в response. Access-Control-Allow-Headers - там то, что ты шлешь в request. Проверь, что в Access-Control-Allow-Origin отсутствует / (slash) вконце.

**Comment by yuristsepaniuk** [comment]
Есть также подозрение, что у тебя с сервера приходит новый куки с новой сессией, берешь и аккуратно смотришь на все requests and responses, если кто-то прислал в ответ новую куку, то проблема не withCredentials. Потому что если куки улетает пустая, то это скорее значит, что права улететь ей есть, но до этого кто-то с сервера прислал в куку пустоту и перетер.

**Comment by yuristsepaniuk** [comment]
Есть ли какие-либо exceptions в developer console на стороне браузера?

**Comment by sergey-moiseyenko** [comment]
нет

**Comment by sergey-moiseyenko** [comment]
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept, Cache-Control, Expires, данные заголовки подключены.

**Comment by sergey-moiseyenko** [comment]
Юра, я нашел, в чем была трабла, накосячил с router-ом и пасспортом

**Comment by yuristsepaniuk** [comment]
@sergey-moiseyenko 👍
